#pragma once

/* Programmer has to ensure the VALUE is valid */
#define SET_REG_FIELD(REG, FIELD, VALUE)                              \
    do {                                                              \
        (REG) = ((REG) & ~(FIELD##_MASK)) | ((VALUE) << FIELD##_POS); \
    } while (0)

#define GET_REG_FIELD(REG, FIELD) (((REG) & FIELD##_MASK) >> FIELD##_POS)

#define DEFINE_REG_FIELD(FIELD, POS, WIDTHMASK) \
    enum { FIELD##_POS = (POS), FIELD##_MASK = ((WIDTHMASK) << (POS)) }



struct gpio {
    volatile unsigned long CRL;
    volatile unsigned long CRH;
    volatile unsigned long IDR;
    volatile unsigned long ODR;
    volatile unsigned long BSRR;
    volatile unsigned long BRR;
    volatile unsigned long LCKR;
};

DEFINE_REG_FIELD(GPIO_CRL_MODE0, 0, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF0, 2, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE1, 4, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF1, 6, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE2, 8, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF2, 10, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE3, 12, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF3, 14, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE4, 16, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF4, 18, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE5, 20, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF5, 22, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE6, 24, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF6, 26, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_MODE7, 28, 0x3);
DEFINE_REG_FIELD(GPIO_CRL_CNF7, 30, 0x3);

DEFINE_REG_FIELD(GPIO_CRH_MODE8, 0, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF8, 2, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE9, 4, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF9, 6, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE10, 8, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF10, 10, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE11, 12, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF11, 14, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE12, 16, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF12, 18, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE13, 20, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF13, 22, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE14, 24, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF14, 26, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_MODE15, 28, 0x3);
DEFINE_REG_FIELD(GPIO_CRH_CNF15, 30, 0x3);

#define GPIOA_BASE (0x40010800)
#define GPIOA ((struct gpio *) GPIOA_BASE)

#define GPIOB_BASE (0x40010C00)
#define GPIOB ((struct gpio *) GPIOB_BASE)

#define GPIOC_BASE (0x40011000)
#define GPIOC ((struct gpio *) GPIOC_BASE)

struct rcc {
    volatile unsigned long CR;
    volatile unsigned long CFGR;
    volatile unsigned long CIR;
    volatile unsigned long APB2RSTR;
    volatile unsigned long APB1RSTR;
    volatile unsigned long AHBENR;
    volatile unsigned long APB2ENR;
    volatile unsigned long APB1ENR;
    volatile unsigned long BDCR;
    volatile unsigned long CSR;
};


DEFINE_REG_FIELD(RCC_CR_HSION, 0, 0x1);
DEFINE_REG_FIELD(RCC_CR_HSIRDY, 1, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(RCC_CR_HSITRIM, 3, 0x1f);
DEFINE_REG_FIELD(RCC_CR_HSICAL, 8, 0xff);
DEFINE_REG_FIELD(RCC_CR_HSEON, 16, 0x1);
DEFINE_REG_FIELD(RCC_CR_HSERDY, 17, 0x1);
DEFINE_REG_FIELD(RCC_CR_HSEBYP, 18, 0x1);
DEFINE_REG_FIELD(RCC_CR_CSSON, 19, 0x1);
/* Reserved : 4 */
DEFINE_REG_FIELD(RCC_CR_PLLON, 24, 0x1);
DEFINE_REG_FIELD(RCC_CR_PLLRDY, 25, 0x1);

DEFINE_REG_FIELD(RCC_CFGR_SW, 0, 0x3);
DEFINE_REG_FIELD(RCC_CFGR_SWS, 2, 0x3);
DEFINE_REG_FIELD(RCC_CFGR_HPRE, 4, 0xf);
DEFINE_REG_FIELD(RCC_CFGR_PPRE1, 8, 0x7);
DEFINE_REG_FIELD(RCC_CFGR_PPRE2, 11, 0x7);
DEFINE_REG_FIELD(RCC_CFGR_ADCPRE, 14, 0x3);
DEFINE_REG_FIELD(RCC_CFGR_PLLSRC, 16, 0x1);
DEFINE_REG_FIELD(RCC_CFGR_PLLXTPRE, 17, 0x1);
DEFINE_REG_FIELD(RCC_CFGR_PLLMUL, 18, 0xf);
DEFINE_REG_FIELD(RCC_CFGR_USBPRE, 22, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(RCC_CFGR_MCO, 24, 0x7);
/* Reserved : 5 */

DEFINE_REG_FIELD(RCC_APB2ENR_AFIOEN, 0, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(RCC_APB2ENR_IOPAEN, 2, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_IOPBEN, 3, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_IOPCEN, 4, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_IOPDEN, 5, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_IOPEEN, 6, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_IOPFEN, 7, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_IOPGEN, 8, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_ADC1EN, 9, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_ADC2EN, 10, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_TIM1EN, 11, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_SPI1EN, 12, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_TIM8EN, 13, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_USART1EN, 14, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_ADC3EN, 15, 0x1);
/* Reserved : 3 */
DEFINE_REG_FIELD(RCC_APB2ENR_TIM9EN, 19, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_TIM10EN, 20, 0x1);
DEFINE_REG_FIELD(RCC_APB2ENR_TIM11EN, 21, 0x1);
/* Reserved : 10 */

DEFINE_REG_FIELD(RCC_APB1ENR_TIM2EN, 0, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM3EN, 1, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM4EN, 2, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM5EN, 3, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM6EN, 4, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM7EN, 5, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM12EN, 6, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM13EN, 7, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_TIM14EN, 8, 0x1);
/* Reserved : 2 */
DEFINE_REG_FIELD(RCC_APB1ENR_WWDGEN, 11, 0x1);
/* Reserved : 2 */
DEFINE_REG_FIELD(RCC_APB1ENR_SPI2EN, 14, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_SPI3EN, 15, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(RCC_APB1ENR_USART2EN, 17, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_USART3EN, 18, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_UART4EN, 19, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_UART5EN, 20, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_I2C1EN, 21, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_I2C2EN, 22, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_USBEN, 23, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(RCC_APB1ENR_CANEN, 25, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(RCC_APB1ENR_BKPEN, 27, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_PWREN, 28, 0x1);
DEFINE_REG_FIELD(RCC_APB1ENR_DACEN, 29, 0x1);

#define RCC_BASE (0x40021000)
#define RCC ((struct rcc *) RCC_BASE)

enum {
    CNF_INPUT_ANALOG,
    CNF_INPUT_FLOATING,
    CNF_INPUT_PUSH_PULL,
    CNF_INPUT_RESERVED
};

enum {
    CNF_OUTPUT_GP_PUSH_PULL,
    CNF_OUTPUT_GP_OPEN,
    CNF_OUTPUT_AF_PUSH_PULL,
    CNF_OUTPUT_AF_OPEN
};

enum { MODE_INPUT, MODE_OUTPUT_10MHz, MODE_OUTPUT_2MHz, MODE_OUTPUT_50MHz };

#define GPIO_CONF(CNF, MODE) (((CNF) << 2) | (MODE))


struct usart {
    volatile unsigned long SR;
    volatile unsigned long DR;
    volatile unsigned long BRR;
    volatile unsigned long CR1;
    volatile unsigned long CR2;
    volatile unsigned long CR3;
    volatile unsigned long GTPR;
};

#define USART1_BASE (0x40013800)
#define USART1 ((struct usart *) USART1_BASE)
#define USART_SR_RXNE (1 << 5)
#define USART_SR_TC (1 << 6)
#define USART_SR_TXE (1 << 7)
#define USART_CR1_UE (1 << 13)
#define USART_CR1_TE (1 << 3)
#define USART_CR1_RE (1 << 2)

struct flash_regs {
    volatile unsigned long ACR;
    volatile unsigned long KEYR;
    volatile unsigned long OPTKEYR;
    volatile unsigned long SR;
    volatile unsigned long CR;
    volatile unsigned long AR;
    volatile unsigned long RESERVED;
    volatile unsigned long OBR;
    volatile unsigned long WRPR;
    /* something more */
};

#define FLASH_BASE (0x40022000)
#define FLASH ((struct flash_regs *) FLASH_BASE)

DEFINE_REG_FIELD(FLASH_ACR_LATENCY, 0, 0b111);
DEFINE_REG_FIELD(FLASH_ACR_HLFCYA, 3, 1);
DEFINE_REG_FIELD(FLASH_ACR_PRFTBE, 4, 1);
DEFINE_REG_FIELD(FLASH_ACR_PRFTBS, 5, 1);

struct tim {
    volatile unsigned long CR1;
    volatile unsigned long CR2;
    volatile unsigned long SMCR;
    volatile unsigned long DIER;
    volatile unsigned long SR;
    volatile unsigned long EGR;
    volatile unsigned long CCMR1;
    volatile unsigned long CCMR2;
    volatile unsigned long CCER;
    volatile unsigned long CNT;
    volatile unsigned long PSC;
    volatile unsigned long ARR;
    volatile unsigned long RESERVED0;
    volatile unsigned long CCR1;
    volatile unsigned long CCR2;
    volatile unsigned long CCR3;
    volatile unsigned long CCR4;
    volatile unsigned long RESERVED1;
    volatile unsigned long DCR;
    volatile unsigned long DMAR;
};

DEFINE_REG_FIELD(TIM_CR1_CEN, 0, 0x1);
DEFINE_REG_FIELD(TIM_CR1_UDIS, 1, 0x1);
DEFINE_REG_FIELD(TIM_CR1_URS, 2, 0x1);
DEFINE_REG_FIELD(TIM_CR1_OPM, 3, 0x1);
DEFINE_REG_FIELD(TIM_CR1_DIR, 4, 0x1);
DEFINE_REG_FIELD(TIM_CR1_CMS, 5, 0x3);
DEFINE_REG_FIELD(TIM_CR1_ARPE, 7, 0x1);
DEFINE_REG_FIELD(TIM_CR1_CKD, 8, 0x3);

DEFINE_REG_FIELD(TIM_DIER_UIE, 0, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC1IE, 1, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC2IE, 2, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC3IE, 3, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC4IE, 4, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(TIM_DIER_TIE, 6, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(TIM_DIER_UDE, 8, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC1DE, 9, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC2DE, 10, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC3DE, 11, 0x1);
DEFINE_REG_FIELD(TIM_DIER_CC4DE, 12, 0x1);
DEFINE_REG_FIELD(TIM_DIER_COMDE, 13, 0x1);
DEFINE_REG_FIELD(TIM_DIER_TDE, 14, 0x1);

DEFINE_REG_FIELD(TIM_SR_UIF, 0, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC1IF, 1, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC2IF, 2, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC3IF, 3, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC4IF, 4, 0x1);
/* Reserved : 1 */
DEFINE_REG_FIELD(TIM_SR_TIF, 6, 0x1);
/* Reserved : 2 */
DEFINE_REG_FIELD(TIM_SR_CC1OF, 9, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC2OF, 10, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC3OF, 11, 0x1);
DEFINE_REG_FIELD(TIM_SR_CC4OF, 12, 0x1);

#define TIM2_BASE (0x40000000)
#define TIM2 ((struct tim *) TIM2_BASE)

#define SETENA0 (*(volatile unsigned long *) 0xE000E100)
#define ICSR (*(volatile unsigned long *) 0xE000ED04)

DEFINE_REG_FIELD(ICSR_PENDSVSET, 28, 0x1);

#define SYSTICK_RELOAD (*(volatile unsigned long *) 0xE000E014)
#define SYSTICK_CURRENT (*(volatile unsigned long *) 0xE000E018)
#define SYSTICK_CONTROL (*(volatile unsigned long *) 0xE000E010)
